version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:18.14.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: .
          paths:
            - .

  run_ui_tests:
    docker:
      - image: cimg/node:18.14.0-browsers
    steps:
      - attach_workspace:
          at: .
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Browser Installation
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Run UI Tests
          command: npm run test:UI

  run_api_tests:
    docker:
      - image: cimg/node:18.14.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Start API Server and Run API Tests
          command: npm run test:API:unix
      - store_artifacts:
          path: api_server.log
          destination: api_server_logs

workflows:
  version: 2
  run_all_tests:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only: main
      - run_ui_tests:
          requires:
            - install_dependencies
          filters:
            branches:
              only: main
      - run_api_tests:
          requires:
            - install_dependencies
          filters:
            branches:
              only: main

