version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
  run_tests:
    docker:
      - image: cimg/node:18.14.0-browsers
    steps:
      - checkout
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check Browser Installation
          command: |
            google-chrome --version
            chromedriver --version
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start API Server and Run API Tests
          command: npm run test:API
          continue-on-error: true
      - run:
          name: Run UI Tests
          command: npm run test:UI
          continue-on-error: true

      - store_artifacts:
          path: api_server.log
          destination: api_server_logs

workflows:
  version: 2
  run_all_tests:
    jobs:
      - run_tests:
          filters:
            branches:
              only: main
