version: 2.1

jobs:
  ui_test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
        name: Debug Chromedriver Path
        command: which chromedriver || echo "Chromedriver not found"
      - run:
          name: Run UI Tests
          command: npm run test:UI

workflows:
  version: 2

  ui_and_api_tests:
    jobs:
      - ui_test:
          filters:
            branches:
              only: UI