version: 2.1

jobs:
  ui_test:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - run:
          name: Install Chrome Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable libnss3 libgconf-2-4
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Install Chromedriver
          command: npm install chromedriver@latest
      - run:
          name: Debug Chromedriver Path
          command: npx chromedriver --version || echo "Chromedriver not found"
      - run:
          name: Run UI Tests
          command: npm run test:UI

workflows:
  version: 2

  ui_and_api_tests:
    jobs:
      - ui_test:
          filters:
            branches:
              only: UI